workspace:
  base: /drone
  path: src

branches:
  - master

pipeline:
  dryrun:
    image: plugins/docker:17.05
    pull: true
    secrets: [ docker_username, docker_password ]
    repo: owncloudci/core
    label_schema:
      - version=${DRONE_BRANCH}
    dry_run: true
    build_args:
      - PHP_VERSION=${PHP_VERSION}
    tags:
      - ${TAG1}
      - ${TAG2}
    when:
      event: [ pull_request ]

  docker:
    image: plugins/docker:17.05
    pull: true
    secrets: [ docker_username, docker_password ]
    repo: owncloudci/core
    label_schema:
      - version=${DRONE_BRANCH}
    build_args:
      - PHP_VERSION=${PHP_VERSION}
    tags:
      - ${TAG1}
      - ${TAG2}
    when:
      event: [ push ]

  microbadger:
    image: plugins/webhook:1
    pull: true
    secrets:
      - source: microbadger_token
        target: plugin_webhook
    when:
      event: [ push ]

  slack:
    image: plugins/slack:1
    pull: true
    secrets: [ slack_webhook ]
    channel: drone
    when:
      status: [ success, failure ]

matrix:
  include:
    - PHP_VERSION: 5.6
      TAG1: 5.6
    - PHP_VERSION: 7.0
      TAG1: 7.0
    - PHP_VERSION: 7.1
      TAG1: latest
      TAG2: 7.1
    - PHP_VERSION: 7.2
      TAG1: 7.2
    - PHP_VERSION: 7.3
      TAG1: 7.3